# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

**Always remember**, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.

In [1]:
# Import pandas
import pandas as pd

In [2]:
# Create a series of three different colours
colours = pd.Series(["Red", "Blue", "Green"])

In [3]:
# View the series of different colours
colours

0      Red
1     Blue
2    Green
dtype: str

In [4]:
# Create a series of three different car types and view it
cars = pd.Series(["Toyota", "BMW", "Honda"])
cars

0    Toyota
1       BMW
2     Honda
dtype: str

In [5]:
# Combine the Series of cars and colours into a DataFrame
car_data = pd.concat([cars, colours], axis=1)
car_data

        0      1
0  Toyota    Red
1     BMW   Blue
2   Honda  Green

In [6]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("C:/Users/msheh/Desktop/AI_ML001/3Logy-NDI-AI-ML-Crash/datasets/car_sales.csv")

In [7]:
car_sales

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,0,1,12/03/2024,Hyundai,Elantra,2018,$33024,2,Abuja
1,1,2,04/08/2024,Hyundai,Elantra,2023,$50741,1,Ibadan
2,2,3,04/11/2024,Toyota,Corolla,2018,$29328,2,Ibadan
3,3,4,22/04/2024,Toyota,RAV4,2019,$57590,5,Kano
4,4,5,04/08/2024,BMW,X3,2020,$15425,2,Enugu
...,...,...,...,...,...,...,...,...,...
95,95,96,11/03/2024,Honda,Accord,2020,"₦35,952.00",5,Lagos
96,96,97,31/07/2024,Honda,Civic,2021,"₦25,014.00",2,Lagos
97,97,98,15/04/2024,BMW,5 Series,2022,"₦45,534.00",4,Lagos
98,98,99,13/07/2024,Kia,Sportage,2021,"₦53,278.00",1,Ibadan
99,99,100,02/10/2024,BMW,3 Series,2020,"₦34,569.00",4,Kano

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [8]:
# Export the DataFrame you created to a .csv file
car_data.to_csv("C:/Users/msheh/Desktop/AI_ML001/3Logy-NDI-AI-ML-Crash/datasets/car_sales_exported.csv", index=False)

In [9]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

Unnamed: 0         int64
sale_id            int64
sale_date            str
brand                str
model                str
year               int64
price_usd            str
quantity_sold      int64
dealership_city      str
dtype: object

In [10]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

       Unnamed: 0     sale_id         year  quantity_sold
count  100.000000  100.000000   100.000000     100.000000
mean    49.500000   50.500000  2021.060000       3.120000
std     29.011492   29.011492     1.762803       1.401875
min      0.000000    1.000000  2018.000000       1.000000
25%     24.750000   25.750000  2020.000000       2.000000
50%     49.500000   50.500000  2021.000000       3.000000
75%     74.250000   75.250000  2022.000000       4.000000
max     99.000000  100.000000  2024.000000       5.000000

In [11]:
# Get information about your DataFrame using info()
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       100 non-null    int64
 1   sale_id          100 non-null    int64
 2   sale_date        100 non-null    str
 3   brand            100 non-null    str
 4   model            100 non-null    str
 5   year             100 non-null    int64
 6   price_usd        100 non-null    str
 7   quantity_sold    100 non-null    int64
 8   dealership_city  100 non-null    str
dtypes: int64(4), str(5)
memory usage: 7.2 KB

What does it show you?

In [12]:
# Create a Series of different numbers and find the mean of them
numbers = pd.Series([10, 20, 30, 40, 50])
numbers.mean()

np.float64(30.0)

In [13]:
# Create a Series of different numbers and find the sum of them
numbers.sum()

np.int64(150)

In [14]:
# List out all the column names of the car sales DataFrame
car_sales.columns

Index(['Unnamed: 0', 'sale_id', 'sale_date', 'brand', 'model', 'year',
       'price_usd', 'quantity_sold', 'dealership_city'],
      dtype='str')

In [15]:
# Find the length of the car sales DataFrame
len(car_sales)

100

In [16]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head()

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,0,1,12/03/2024,Hyundai,Elantra,2018,$33024,2,Abuja
1,1,2,04/08/2024,Hyundai,Elantra,2023,$50741,1,Ibadan
2,2,3,04/11/2024,Toyota,Corolla,2018,$29328,2,Ibadan
3,3,4,22/04/2024,Toyota,RAV4,2019,$57590,5,Kano
4,4,5,04/08/2024,BMW,X3,2020,$15425,2,Enugu

In [17]:

# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,0,1,12/03/2024,Hyundai,Elantra,2018,$33024,2,Abuja
1,1,2,04/08/2024,Hyundai,Elantra,2023,$50741,1,Ibadan
2,2,3,04/11/2024,Toyota,Corolla,2018,$29328,2,Ibadan
3,3,4,22/04/2024,Toyota,RAV4,2019,$57590,5,Kano
4,4,5,04/08/2024,BMW,X3,2020,$15425,2,Enugu
5,5,6,17/02/2024,Ford,Fusion,2019,$29110,3,Lagos
6,6,7,23/01/2024,BMW,3 Series,2020,$37541,5,Port Harcourt

In [18]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
95,95,96,11/03/2024,Honda,Accord,2020,"₦35,952.00",5,Lagos
96,96,97,31/07/2024,Honda,Civic,2021,"₦25,014.00",2,Lagos
97,97,98,15/04/2024,BMW,5 Series,2022,"₦45,534.00",4,Lagos
98,98,99,13/07/2024,Kia,Sportage,2021,"₦53,278.00",1,Ibadan
99,99,100,02/10/2024,BMW,3 Series,2020,"₦34,569.00",4,Kano

In [19]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Unnamed: 0                  3
sale_id                     4
sale_date          22/04/2024
brand                  Toyota
model                    RAV4
year                     2019
price_usd              $57590
quantity_sold               5
dealership_city          Kano
Name: 3, dtype: object

In [20]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Unnamed: 0                  3
sale_id                     4
sale_date          22/04/2024
brand                  Toyota
model                    RAV4
year                     2019
price_usd              $57590
quantity_sold               5
dealership_city          Kano
Name: 3, dtype: object

Notice how they're the same? Why do you think this is? 

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [21]:
# Select the "price_usd" column from the car sales DataFrame
car_sales["price_usd"]

0         $33024
1         $50741
2         $29328
3         $57590
4         $15425
         ...
95    ₦35,952.00
96    ₦25,014.00
97    ₦45,534.00
98    ₦53,278.00
99    ₦34,569.00
Name: price_usd, Length: 100, dtype: str

In [22]:
# Convert the column i.e `price_usd` to an int dtype using the `.str.replace()` method
#car_sales["price_usd"] = car_sales["price_usd"].str.replace(r"[$,]", '', regex=True).astype(int)
# Strip the currency symbols and commas, convert to float first to handle decimals correctly
car_sales["price_usd"] = car_sales["price_usd"].str.replace(r"[₦$,]", '', regex=True).astype(float).astype(int)

In [23]:
car_sales["price_usd"]

0     33024
1     50741
2     29328
3     57590
4     15425
      ...
95    35952
96    25014
97    45534
98    53278
99    34569
Name: price_usd, Length: 100, dtype: int64

In [24]:
# Find the mean of the "price_usd" column in the car sales DataFrame
car_sales["price_usd"].mean()

np.float64(34658.72)

In [25]:
# Select the rows with over 100,000 dollar on the `price_usd`
car_sales[car_sales["price_usd"] > 100000]

Empty DataFrame
Columns: [Unnamed: 0, sale_id, sale_date, brand, model, year, price_usd, quantity_sold, dealership_city]
Index: []

In [26]:
# Create a new column called `total_amount_sold` by multiplying the `price_usd` and `quantity_sold`
car_sales["total_amount_sold"] = car_sales["price_usd"] * car_sales["quantity_sold"]

In [27]:
car_sales

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,total_amount_sold
0,0,1,12/03/2024,Hyundai,Elantra,2018,33024,2,Abuja,66048
1,1,2,04/08/2024,Hyundai,Elantra,2023,50741,1,Ibadan,50741
2,2,3,04/11/2024,Toyota,Corolla,2018,29328,2,Ibadan,58656
3,3,4,22/04/2024,Toyota,RAV4,2019,57590,5,Kano,287950
4,4,5,04/08/2024,BMW,X3,2020,15425,2,Enugu,30850
...,...,...,...,...,...,...,...,...,...,...
95,95,96,11/03/2024,Honda,Accord,2020,35952,5,Lagos,179760
96,96,97,31/07/2024,Honda,Civic,2021,25014,2,Lagos,50028
97,97,98,15/04/2024,BMW,5 Series,2022,45534,4,Lagos,182136
98,98,99,13/07/2024,Kia,Sportage,2021,53278,1,Ibadan,53278
99,99,100,02/10/2024,BMW,3 Series,2020,34569,4,Kano,138276

In [28]:
# Group columns of the car sales DataFrame by the `brand` column and find the average
car_sales.groupby("brand").mean(numeric_only=True)

,Unnamed: 0,sale_id,year,price_usd,quantity_sold,total_amount_sold
brand,,,,,,
BMW,59.500000,60.500000,2021.250000,33873.550000,3.850000,129244.050000
Ford,41.500000,42.500000,2021.000000,32148.125000,3.375000,114551.875000
Honda,56.777778,57.777778,2021.388889,31955.611111,3.055556,95486.000000
Hyundai,39.466667,40.466667,2021.466667,36899.533333,2.933333,108506.133333
Kia,54.500000,55.500000,2021.000000,36242.785714,2.714286,97100.500000
Mercedes,45.333333,46.333333,2020.555556,32952.111111,3.111111,90988.333333
Toyota,40.187500,41.187500,2020.437500,37409.625000,2.687500,100887.750000

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [29]:
# Remove the punctuation from price column
#car_sales["price_usd"] = car_sales["price_usd"].str.replace(r'[₦\$, text{,}]', '', regex=True)
# Check the data type and the first few rows
# This tells you the data type (int64 means it's already a number!)
print(car_sales["price_usd"].dtype)
car_sales.head()

int64

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,total_amount_sold
0,0,1,12/03/2024,Hyundai,Elantra,2018,33024,2,Abuja,66048
1,1,2,04/08/2024,Hyundai,Elantra,2023,50741,1,Ibadan,50741
2,2,3,04/11/2024,Toyota,Corolla,2018,29328,2,Ibadan,58656
3,3,4,22/04/2024,Toyota,RAV4,2019,57590,5,Kano,287950
4,4,5,04/08/2024,BMW,X3,2020,15425,2,Enugu,30850

In [30]:
print(car_sales.columns)

Index(['Unnamed: 0', 'sale_id', 'sale_date', 'brand', 'model', 'year',
       'price_usd', 'quantity_sold', 'dealership_city', 'total_amount_sold'],
      dtype='str')

In [31]:
# Check the changes to the price column
car_sales["price_usd"].dtype

dtype('int64')

In [32]:
# Remove the two extra zeros at the end of the price column
car_sales["price_usd"] = car_sales["price_usd"].astype(str).str.replace(r'\.00$', '', regex=True)
car_sales

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,total_amount_sold
0,0,1,12/03/2024,Hyundai,Elantra,2018,33024,2,Abuja,66048
1,1,2,04/08/2024,Hyundai,Elantra,2023,50741,1,Ibadan,50741
2,2,3,04/11/2024,Toyota,Corolla,2018,29328,2,Ibadan,58656
3,3,4,22/04/2024,Toyota,RAV4,2019,57590,5,Kano,287950
4,4,5,04/08/2024,BMW,X3,2020,15425,2,Enugu,30850
...,...,...,...,...,...,...,...,...,...,...
95,95,96,11/03/2024,Honda,Accord,2020,35952,5,Lagos,179760
96,96,97,31/07/2024,Honda,Civic,2021,25014,2,Lagos,50028
97,97,98,15/04/2024,BMW,5 Series,2022,45534,4,Lagos,182136
98,98,99,13/07/2024,Kia,Sportage,2021,53278,1,Ibadan,53278
99,99,100,02/10/2024,BMW,3 Series,2020,34569,4,Kano,138276

In [33]:
# Check the changes to the Price column
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         100 non-null    int64
 1   sale_id            100 non-null    int64
 2   sale_date          100 non-null    str
 3   brand              100 non-null    str
 4   model              100 non-null    str
 5   year               100 non-null    int64
 6   price_usd          100 non-null    str
 7   quantity_sold      100 non-null    int64
 8   dealership_city    100 non-null    str
 9   total_amount_sold  100 non-null    int64
dtypes: int64(5), str(5)
memory usage: 7.9 KB

In [34]:
# Change the datatype of the Price column to integers
car_sales["price_usd"] = car_sales["price_usd"].astype(int)

In [35]:
# Lower the strings of the `brand` column
car_sales["brand"] = car_sales["brand"].str.lower()

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [36]:
# Make lowering the case of the brand column permanent
# Overwrite the 'brand' column with the lowercase version of itself
car_sales["brand"] = car_sales["brand"].str.lower()

In [37]:
# Check the car sales DataFrame
car_sales.head()

,Unnamed: 0,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,total_amount_sold
0,0,1,12/03/2024,hyundai,Elantra,2018,33024,2,Abuja,66048
1,1,2,04/08/2024,hyundai,Elantra,2023,50741,1,Ibadan,50741
2,2,3,04/11/2024,toyota,Corolla,2018,29328,2,Ibadan,58656
3,3,4,22/04/2024,toyota,RAV4,2019,57590,5,Kano,287950
4,4,5,04/08/2024,bmw,X3,2020,15425,2,Enugu,30850

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [38]:
# Import the car sales DataFrame with missing data ("car-sales_missing.csv")

# Check out the new DataFrame
import pandas as pd

# 1. Define the path (using 'r' before the string helps with Windows backslashes
file_path = r"C:/Users/msheh/Desktop/AI_ML001/3Logy-NDI-AI-ML-Crash/datasets/car_sales_missing.csv"

# 2. Use pd.read_csv to actually load the data
car_sales_missing = pd.read_csv(file_path)

# 3. View the result
car_sales_missing

,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.0,Abuja
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.0,Ibadan
2,3,04/11/2024,Toyota,NaN,2018.0,$29328,2.0,Ibadan
3,4,22/04/2024,Toyota,NaN,2019.0,$57590,5.0,Kano
4,5,04/08/2024,BMW,NaN,2020.0,$15425,2.0,Enugu
...,...,...,...,...,...,...,...,...
95,96,NaN,Honda,NaN,2020.0,"?35,952.00",5.0,NaN
96,97,NaN,Honda,NaN,2021.0,"?25,014.00",2.0,NaN
97,98,15/04/2024,BMW,5 Series,2022.0,"?45,534.00",NaN,NaN
98,99,13/07/2024,Kia,Sportage,2021.0,"?53,278.00",NaN,NaN
99,100,02/10/2024,BMW,3 Series,2020.0,"?34,569.00",NaN,Kano

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [39]:
# Fill the quantity column missing values with the mean of the column inplace
# The modern way: Re-assign the column to save the changes
car_sales_missing["quantity_sold"] = car_sales_missing["quantity_sold"].fillna(car_sales_missing["quantity_sold"].mean())

In [40]:
# View the car sales missing DataFrame and verify the changes
# View the first 10 rows to see the filled values
car_sales_missing.head(10)

,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.000000,Abuja
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.000000,Ibadan
2,3,04/11/2024,Toyota,NaN,2018.0,$29328,2.000000,Ibadan
3,4,22/04/2024,Toyota,NaN,2019.0,$57590,5.000000,Kano
4,5,04/08/2024,BMW,NaN,2020.0,$15425,2.000000,Enugu
5,6,17/02/2024,Ford,NaN,2019.0,$29110,3.081395,Lagos
6,7,23/01/2024,BMW,NaN,2020.0,$37541,3.081395,Port Harcourt
7,8,09/10/2024,Hyundai,Sonata,2022.0,$23180,4.000000,Lagos
8,9,26/12/2024,Ford,Escape,2022.0,$38700,5.000000,Abuja
9,10,29/04/2024,Toyota,Corolla,2023.0,$29935,3.000000,Lagos

In [41]:
# Remove the rest of the missing data inplace
# This does the exact same thing but is more "future-proof"
car_sales_missing = car_sales_missing.dropna()

In [42]:
# Verify the missing values are removed by viewing the DataFrame
car_sales_missing.head()

,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.0,Abuja
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.0,Ibadan
7,8,09/10/2024,Hyundai,Sonata,2022.0,$23180,4.0,Lagos
8,9,26/12/2024,Ford,Escape,2022.0,$38700,5.0,Abuja
9,10,29/04/2024,Toyota,Corolla,2023.0,$29935,3.0,Lagos

We'll now start to add columns to our DataFrame.

In [43]:
# Create a "Seats" column where every row has a value of 5
car_sales_missing["Seats"] = 5
car_sales_missing.head()

,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,Seats
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.0,Abuja,5
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.0,Ibadan,5
7,8,09/10/2024,Hyundai,Sonata,2022.0,$23180,4.0,Lagos,5
8,9,26/12/2024,Ford,Escape,2022.0,$38700,5.0,Abuja,5
9,10,29/04/2024,Toyota,Corolla,2023.0,$29935,3.0,Lagos,5

In [44]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
import numpy as np

# 1. Generate random floats between 1.3 and 4.5
# We use len(car_sales) to ensure the list matches the DataFrame length exactly
car_sales_missing["Engine Size"] = np.random.uniform(1.3, 4.5, size=len(car_sales_missing))
car_sales_missing.head()

,sale_id,sale_date,brand,model,year,price_usd,quantity_sold,dealership_city,Seats,Engine Size
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.0,Abuja,5,2.744945
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.0,Ibadan,5,3.351798
7,8,09/10/2024,Hyundai,Sonata,2022.0,$23180,4.0,Lagos,5,3.447006
8,9,26/12/2024,Ford,Escape,2022.0,$38700,5.0,Abuja,5,2.738985
9,10,29/04/2024,Toyota,Corolla,2023.0,$29935,3.0,Lagos,5,1.591941

In [45]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame
# Rename 'quantity_sold' to 'odometer' permanently
car_sales_missing.rename(columns={"quantity_sold": "odometer"}, inplace=True)

# Confirm the name change
print(car_sales_missing.columns)
car_sales_missing

Index(['sale_id', 'sale_date', 'brand', 'model', 'year', 'price_usd',
       'odometer', 'dealership_city', 'Seats', 'Engine Size'],
      dtype='str')

,sale_id,sale_date,brand,model,year,price_usd,odometer,dealership_city,Seats,Engine Size
0,1,12/03/2024,Hyundai,Elantra,2018.0,$33024,2.000000,Abuja,5,2.744945
1,2,04/08/2024,Hyundai,Elantra,2023.0,$50741,1.000000,Ibadan,5,3.351798
7,8,09/10/2024,Hyundai,Sonata,2022.0,$23180,4.000000,Lagos,5,3.447006
8,9,26/12/2024,Ford,Escape,2022.0,$38700,5.000000,Abuja,5,2.738985
9,10,29/04/2024,Toyota,Corolla,2023.0,$29935,3.000000,Lagos,5,1.591941
...,...,...,...,...,...,...,...,...,...,...
87,88,23/07/2024,BMW,X3,2022.0,"?27,742.00",3.081395,Kano,5,4.053336
88,89,22/04/2024,Honda,Civic,2023.0,"?15,363.00",1.000000,Kano,5,2.325855
89,90,07/05/2024,Honda,CR-V,2022.0,"?45,444.00",1.000000,Ibadan,5,3.403869
90,91,28/09/2024,Kia,Rio,2021.0,"?23,738.00",4.000000,Enugu,5,1.861015
99,100,02/10/2024,BMW,3 Series,2020.0,"?34,569.00",3.081395,Kano,5,4.281827

In [46]:
# Remove the last column you added using .drop()
car_sales_missing.drop("odometer", axis=1, inplace=True)

In [47]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable
car_sales_missing_shuffled = car_sales_missing.sample(frac=1)
car_sales_missing_shuffled

,sale_id,sale_date,brand,model,year,price_usd,dealership_city,Seats,Engine Size
11,12,15/12/2024,Honda,Accord,2020.0,"?28,730.00",Enugu,5,2.948965
84,85,17/02/2024,Hyundai,Elantra,2020.0,"?48,780.00",Port Harcourt,5,4.319316
74,75,18/09/2024,BMW,5 Series,2023.0,"?35,557.00",Ibadan,5,3.627378
63,64,09/10/2024,Hyundai,Elantra,2022.0,"?17,361.00",Ibadan,5,2.183225
35,36,30/08/2024,BMW,3 Series,2022.0,"?23,671.00",Ibadan,5,1.756729
...,...,...,...,...,...,...,...,...,...
86,87,21/08/2024,Toyota,Corolla,2019.0,"?46,138.00",Lagos,5,3.198513
43,44,18/07/2024,Kia,Sportage,2018.0,"?25,789.00",Lagos,5,1.433521
40,41,08/02/2024,Honda,Accord,2019.0,"?33,254.00",Abuja,5,4.213325
59,60,08/05/2024,Honda,CR-V,2023.0,"?32,300.00",Kano,5,3.574743
53,54,02/10/2024,Toyota,Camry,2022.0,"?51,896.00",Lagos,5,2.006378

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [48]:
# Reset the indexes of the shuffled DataFrame
car_sales_missing_shuffled.reset_index(drop=True, inplace=True)
car_sales_missing_shuffled

,sale_id,sale_date,brand,model,year,price_usd,dealership_city,Seats,Engine Size
0,12,15/12/2024,Honda,Accord,2020.0,"?28,730.00",Enugu,5,2.948965
1,85,17/02/2024,Hyundai,Elantra,2020.0,"?48,780.00",Port Harcourt,5,4.319316
2,75,18/09/2024,BMW,5 Series,2023.0,"?35,557.00",Ibadan,5,3.627378
3,64,09/10/2024,Hyundai,Elantra,2022.0,"?17,361.00",Ibadan,5,2.183225
4,36,30/08/2024,BMW,3 Series,2022.0,"?23,671.00",Ibadan,5,1.756729
...,...,...,...,...,...,...,...,...,...
65,87,21/08/2024,Toyota,Corolla,2019.0,"?46,138.00",Lagos,5,3.198513
66,44,18/07/2024,Kia,Sportage,2018.0,"?25,789.00",Lagos,5,1.433521
67,41,08/02/2024,Honda,Accord,2019.0,"?33,254.00",Abuja,5,4.213325
68,60,08/05/2024,Honda,CR-V,2023.0,"?32,300.00",Kano,5,3.574743
69,54,02/10/2024,Toyota,Camry,2022.0,"?51,896.00",Lagos,5,2.006378

Notice the index numbers have been changed to have order (start from 0).

## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html). 

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.