# Exercise

In [3]:
# Import pandas library, aliased as `pd`
import pandas as pd
import numpy as np
import matplotlib as plt

# Solution

In [3]:
# Import dataset
data = pd.read_csv("C:/Users/msheh/Desktop/AI_ML001/3Logy-NDI-AI-ML-Crash/datasets/retail_transactions_200.csv")

In [6]:
data.head(10)

,ID,Customer_Age,Gender,Product_Category,Purchase_Amount_USD,Payment_Method,Satisfaction_1_to_5
0,1,28,Male,Furniture,775,Cash,3
1,2,27,Male,Beauty,57,Cash,3
2,3,26,Male,Clothing,114,Mobile,3
3,4,33,Female,Clothing,107,Mobile,4
4,5,21,Male,Groceries,61,Card,3
5,6,34,Female,Electronics,247,Card,3
6,7,43,Female,Beauty,46,Cash,5
7,8,50,Male,Groceries,45,Mobile,4
8,9,44,Male,Electronics,223,Mobile,3
9,10,39,Male,Clothing,62,Card,4

In [5]:
from pathlib import Path
print(Path.cwd())

C:\Users\msheh\Desktop\AI_ML001

In [5]:
data

,ID,Customer_Age,Gender,Product_Category,Purchase_Amount_USD,Payment_Method,Satisfaction_1_to_5
0,1,28,Male,Furniture,775,Cash,3
1,2,27,Male,Beauty,57,Cash,3
2,3,26,Male,Clothing,114,Mobile,3
3,4,33,Female,Clothing,107,Mobile,4
4,5,21,Male,Groceries,61,Card,3
...,...,...,...,...,...,...,...
195,196,44,Male,Electronics,351,Card,5
196,197,47,Male,Clothing,66,Mobile,4
197,198,54,Female,Clothing,82,Card,4
198,199,42,Male,Groceries,44,Cash,3
199,200,46,Female,Electronics,402,Cash,4

In [7]:
#Data types
data.dtypes

ID                     int64
Customer_Age           int64
Gender                   str
Product_Category         str
Purchase_Amount_USD    int64
Payment_Method           str
Satisfaction_1_to_5    int64
dtype: object

In [8]:
# This returns the column names as a list
# Index is a data structure used by Pandas to store labels for rows and columns. i.e here we've column index
data.columns

Index(['ID', 'Customer_Age', 'Gender', 'Product_Category',
       'Purchase_Amount_USD', 'Payment_Method', 'Satisfaction_1_to_5'],
      dtype='str')

In [9]:
# This returns the index
data.index

RangeIndex(start=0, stop=200, step=1)

In [11]:
#If you're interested in understanding the dimensionality of the DataFrame, we can use the df.shape method. The code looks like this:
data.shape
print("df_houses shape:", data.shape)

df_houses shape: (200, 7)