In [26]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2026-04-01 14:39:15.356132

**Visit here for more**: https://scikit-learn.org/stable/modules/linear_model.html#

## What is Scikit-Learn (sklearn)?

[Scikit-Learn](https://scikit-learn.org/stable/index.html), also referred to as `sklearn`, is an open-source Python machine learning library.

It's built on top on NumPy (Python library for numerical computing) and Matplotlib (Python library for data visualization).

<img src="../images/sklearn-6-step-ml-framework-tools-scikit-learn-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>

## Why Scikit-Learn?

Although the fields of data science, machine learning and AI are vast, the main goal is finding patterns within data and then using those patterns to make predictions.

And there are certain categories which a majority of problems fall into.

If you're trying to create a machine learning model to predict whether an email is spam and or not spam, you're working on a [classification problem](https://en.wikipedia.org/wiki/Statistical_classification#Binary_and_multiclass_classification) (whether something is one thing or another).

If you're trying to create a machine learning model to predict the price of houses given their characteristics, you're working on a [regression problem](https://en.wikipedia.org/wiki/Regression_analysis) (predicting a number).

If you're trying to get a machine learning algorithm to group together similar samples (that you don't necessarily know which should go together), you're working on a [clustering problem](https://developers.google.com/machine-learning/clustering/overview).

Once you know what kind of problem you're working on, there are also similar steps you'll take for each. 

Steps like splitting the data into different sets, one for your machine learning algorithms to learn on (the training set) and another to test them on (the testing set).

Choosing a machine learning model and then evaluating whether or not your model has learned anything.

Scikit-Learn offers Python implementations for doing all of these kinds of tasks (from preparing data to modelling data). Saving you from having to build them from scratch.`

## What does this notebook cover?

The Scikit-Learn library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses some of the main use cases of the library.

More specifically, we'll cover:

<img src="../images/sklearn-workflow-title.png" alt="a 6 step scikit-learn workflow"/>

0. An end-to-end Scikit-Learn worfklow
1. Getting the data ready
2. Choosing the right maching learning estimator/aglorithm/model for your problem
3. Fitting your chosen machine learning model to data and using it to make a prediction
4. Evaluting a machine learning model
5. Improving predictions through experimentation (hyperparameter tuning)
6. Saving and loading a pretrained model
7. Putting it all together in a pipeline

> **Note:** All of the steps in this notebook are focused on [**supervised learning**](https://en.wikipedia.org/wiki/Supervised_learning) (having data and labels). The other side of supervised learning is [**unsupervised learning**](https://en.wikipedia.org/wiki/Unsupervised_learning) (having data but no labels). 

After going through it, you'll have the base knolwedge of Scikit-Learn you need to keep moving forward.

## Where can I get help?

If you get stuck or think of something you'd like to do which this notebook doesn't cover, don't fear!

The recommended steps you take are:
1. **Try it** - Since Scikit-Learn has been designed with usability in mind, your first step should be to use what you know and try figure out the answer to your own question (getting it wrong is part of the process). If in doubt, run your code.
2. **Press SHIFT+TAB** - You can see the docstring of a function (information on what the function does) by pressing **SHIFT + TAB** inside it. Doing this is a good habit to develop. It'll improve your research skills and give you a better understanding of the library. 
3. **Search for it** - If trying it on your own doesn't work, since someone else has probably tried to do something similar, try searching for your problem. You'll likely end up in 1 of 2 places:
    * [Scikit-Learn documentation/user guide](https://scikit-learn.org/stable/user_guide.html) - the most extensive resource you'll find for Scikit-Learn information.
    * [Stack Overflow](https://stackoverflow.com/) - this is the developers Q&A hub, it's full of questions and answers of different problems across a wide range of software development topics and chances are, there's one related to your problem.
    * [ChatGPT](https://chat.openai.com/) - ChatGPT is very good at explaining code, however, it can make mistakes. Best to verify the code it writes first before using it. Try asking "Can you explain the following code for me? {your code here}" and then continue with follow up questions from there. Avoid blindly trusting code you didn't write for yourself.
    
An example of searching for a Scikit-Learn solution might be:

> "how to tune the hyperparameters of a sklearn model"

Searching this on Google leads to the Scikit-Learn documentation for the `GridSearchCV` function: http://scikit-learn.org/stable/modules/grid_search.html

The next steps here are to read through the documentation, check the examples and see if they line up to the problem you're trying to solve. If they do, **rewrite the code** to suit your needs, run it, and see what the outcomes are.

4. **Ask for help** - If you've been through the above 3 steps and you're still stuck, you might want to ask your question on [Stack Overflow](https://www.stackoverflow.com) or in the ZTM Machine Learning and AI Discord channel. Be as specific as possible and provide details on what you've tried.

**Remember, you don't have to learn all of the functions off by heart to begin with**. 

What's most important is continually asking yourself, "what am I trying to do with the data?".

Start by answering that question and then practicing finding the code which does it.

Let's get started.

First we'll import the libraries we've been using previously.

We'll also check the version of `sklearn` we've got.

In [27]:
# Standard imports
# %matplotlib inline # No longer required in newer versions of Jupyter (2022+)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import sklearn
print(f"Using Scikit-Learn version: {sklearn.__version__} (materials in this notebook require this version or newer).")

Using Scikit-Learn version: 1.8.0 (materials in this notebook require this version or newer).

## 0. An end-to-end Scikit-Learn workflow

Before we get in-depth, let's quickly check out what an end-to-end Scikit-Learn workflow might look like.

Once we've seen an end-to-end workflow, we'll dive into each step a little deeper.

Specifically, we'll get hands-on with the following steps:
1. Getting data ready (split into features and labels, prepare train and test steps)
2. Choosing a model for our problem
3. Fit the model to the data and use it to make a prediction
4. Evaluate the model
5. Experiment to improve
6. Save a model for someone else to use

> **Note:** The following section is a bit information heavy but it is an end-to-end workflow. We'll go through it quite swiftly but we'll break it down more throughout the rest of the notebook. And since Scikit-Learn is such a vast library, capable of tackling many problems, the workflow we're using is only one example of how you can use it.

## 1. Getting the data ready

Data doesn't always come ready to use with a Scikit-Learn machine learning model.

Three of the main steps you'll often have to take are:
* Splitting the data into features (usually `X`) and labels (usually `y`).
* Splitting the data into training and testing sets (and possibly a validation set).
* Filling (also called imputing) or disregarding missing values.
* Converting non-numerical values to numerical values (also call feature encoding).

Let's see an example.

In [28]:
# Load data directly from URL (requires raw form on GitHub, source: https://github.com/devmab24/master/data/heart-disease.csv)
# heart_disease = pd.read_csv("https://github.com/devmab24/master/data/diabetes_dataset.csv")
# Load data from local directory
diabetes_disease = pd.read_csv("C:/Users/M.faisal/Desktop/ai_ml/ai_ml_projects/datasets/diabetes_dataset.csv")
diabetes_disease.head(3)

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
0,1,52,0,30.239636,149,113,115,0.312886,1
1,2,53,1,30.932781,71,39,104,0.389526,0
2,3,21,0,45.092714,161,67,151,1.205869,0

Here, each row is a different patient and all columns except `Outcome` are different patient characteristics. 

The `Outcome` column indicates whether the patient is diabetic (`Outcome=1`) or not (`Outcome=0`), this is our "label" columnm, the variable we're going to try and predict.

The rest of the columns (often called features) are what we'll be using to predict the `Outcome` value.

> **Note:** It's a common custom to save features to a varialbe `X` and labels to a variable `y`. In practice, we'd like to use the `X` (features) to build a predictive algorithm to predict the `y` (labels).

In [29]:
# Splitting the data into X_feature & y_outcome
# Create X (all the feature columns)
X = diabetes_disease.drop("Outcome", axis=1)

# Create y (the target column)
y = diabetes_disease["Outcome"]

# Check the head of the features DataFrame
X.head()

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction
0,1,52,0,30.239636,149,113,115,0.312886
1,2,53,1,30.932781,71,39,104,0.389526
2,3,21,0,45.092714,161,67,151,1.205869
3,4,39,0,47.795530,101,165,184,0.595201
4,5,22,1,20.718108,160,158,116,0.974248

In [30]:
# Check the head and the value counts of the labels 
y.head(), y.value_counts()

(0    1
 1    0
 2    0
 3    1
 4    1
 Name: Outcome, dtype: int64,
 Outcome
 0    55
 1    45
 Name: count, dtype: int64)

One of the most important practices in machine learning is to split datasets into training and test sets.

As in, a model will **train on the training set** to learn patterns and then those patterns can be **evaluated on the test set**.

Crucially, a model should **never** see testing data during training.

This is equivalent to a student studying course materials during the semester (training set) and then testing their abilities on the following exam (testing set).

Scikit-learn provides the [`sklearn.model_selection.train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) method to split datasets in training and test sets.

> **Note:** A common practice to use an 80/20 or 70/30 or 75/25 split for training/testing data. There is also a third set, known as a validation set (e.g. 70/15/15 for training/validation/test) for hyperparamter tuning on but for now we'll focus on training and test sets.

In [31]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.25) # by default train_test_split uses 25% of the data for the test set

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((75, 8), (25, 8), (75,), (25,))

#### 2. Choose the model and hyperparameters

Choosing a model often depends on the type of problem you're working on.

For example, there are different models that Scikit-Learn recommends whether you're working on a classification or regression problem.

You can see a map breaking down the [different kinds of model options and recommendations in the Scikit-Learn documentation](https://scikit-learn.org/stable/machine_learning_map.html).

Scikit-Learn refers to models as "estimators", however, they are often also referred to as `model` or `clf` (short for classifier).

A model's hyperparameters are settings you can change to adjust it for your problem, much like knobs(rounded projecting parts acting as handles for doors, drawers, or cabinets, or as control mechanisms on appliances) on an oven you can tune to cook your favourite dish.

In [32]:
# Since we're working on a classification problem, we'll start with a RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

In [33]:
# View the current hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

We'll leave this as is for now, as Scikit-Learn models generally have good default settings.

**Visit the documentation for more**: https://scikit-learn.org/1.5/modules/generated/sklearn.ensemble.RandomForestClassifier.html

#### 3. Fit the model to the data and use it to make a prediction

Fitting a model to a dataset involves passing it the data and asking it to figure out the patterns.

If there are labels (supervised learning), the model tries to work out the relationship between the data and the labels. 

If there are no labels (unsupervised learning), the model tries to find patterns and group similar samples together.

Most Scikit-Learn models have the [`fit(X, y)`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.fit) method built-in, where the `X` parameter is the features and the `y` parameter is the labels.

In our case, we start by fitting a model on the training split (`X_train`, `y_train`).

In [34]:
clf.fit(X=X_train, y=y_train)

RandomForestClassifier()

#### Use the model to make a prediction

The whole point of training a machine learning model is to use it to make some kind of prediction in the future.

Once your model instance is trained, you can use the [`predict()`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.predict) method to predict a target value given a set of features. 

In other words, use the model, along with some new, unseen and unlabelled data to predict the label.

> **Note:** Data you predict on should be in the same shape and format as data you trained on.

In [35]:
# This doesn't work... incorrect shapes
# y_label = clf.predict(np.array([0, 2, 3, 4]))

Oh no! 

We get a `ValueError` (mismatched shapes):

```
ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

This happens because we're **trying to make predictions on data that is in a different format to the data our model was trained on**.

Since our model was trained on data from `X_train`, predictions should be made on data in the same format and shape as `X_train`.

Our goal in many machine learning problems is to use patterns learned from the training data to make predictions on the test data (or future unseen data).

In [36]:
# In order to predict a label, data has to be in the same shape as X_train
X_test.head()

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction
88,89,74,0,33.137225,174,178,173,1.121047
27,28,36,0,19.369928,164,155,164,1.812039
19,20,44,1,21.070217,102,253,128,0.989133
99,100,40,0,37.899312,138,215,91,0.907850
8,9,52,0,26.506155,119,195,178,2.018585

In [37]:
# Use the model to make a prediction on the test data (further evaluation)
y_preds = clf.predict(X=X_test)

In [38]:
# def mulptiply(score):
#     """Optional docstring describing the function."""
#     # Function body starts here, all lines must be indented
#     multiple = score * 2
#     return multiple  # Optional return statement

In [39]:
mulptiply(score=5)

10

#### 4. Evaluate the model

Now we've made some predictions, we can start to use some more Scikit-Learn methods to figure out how good our model is. 

Each model or estimator has a built-in [`score()`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.score) method. 

This method compares how well the model was able to learn the patterns between the features and labels.

The `score()` method for each model uses a standard evaluation metric to measure your model's results.

In the case of a classifier (our model), one of the most common evaluation metrics is [accuracy](https://scikit-learn.org/stable/modules/model_evaluation.html#accuracy-score) (the fraction of correct predictions out of total predictions).

Let's check out our model's accuracy on the training set.

In [40]:
# Evaluate the model on the training set
train_acc = clf.score(X=X_train, y=y_train)
print(f"The model's accuracy on the training dataset is: {train_acc*100}%")

The model's accuracy on the training dataset is: 100.0%

Woah! Looks like our model does pretty well on the training dataset.

This is because it has a chance to see both data *and* labels.

How about the test dataset?

In [41]:
# Evaluate the model on the test set
test_acc = clf.score(X=X_test, y=y_test)
print(f"The model's accuracy on the testing dataset is: {test_acc*100:.2f}%")

The model's accuracy on the testing dataset is: 44.00%

Hmm, looks like our model's accuracy is a bit less on the test dataset than the training dataset.

This is quite often the case, because remember, a model has never seen the testing examples before.

There are also a number of other evaluation methods we can use for our classification models.

All of the following classification metrics come from the [`sklearn.metrics`](https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics) module:
* [`classification_report(y_true, y_true)`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html#sklearn.metrics.classification_report) - Builds a text report showing various classification metrics such as [precision, recall](https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html) and F1-score.
* [`confusion_matrix(y_true, y_pred)`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html#sklearn.metrics.confusion_matrix) - Create a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) to compare predictions to truth labels.
* [`accuracy_score(y_true, y_pred)`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score) - Find the accuracy score (the default metric) for a classifier.

All metrics have the following in common: they compare a model's predictions (`y_pred`) to truth labels (`y_true`).

In [42]:
y_test

88    1
27    1
19    1
99    0
8     1
0     1
33    0
86    0
70    0
73    1
15    0
80    0
64    0
98    0
47    0
78    0
94    0
68    1
96    1
20    0
44    1
74    0
18    1
40    1
49    0
Name: Outcome, dtype: int64

In [43]:
y_preds

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1])

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Create a classification report
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50        14
           1       0.36      0.36      0.36        11

    accuracy                           0.44        25
   macro avg       0.43      0.43      0.43        25
weighted avg       0.44      0.44      0.44        25

The **classification report** above evaluates how well the model is predicting two classes: **0** and **1**.

Let’s break it down in a simple, beginner-friendly way.

## What each term means

### 1. **Precision**

> Out of all the times the model predicted a class, how many were correct?

* Class 0 → **0.55** → 55% of predicted 0s were correct
* Class 1 → **0.14** → Only 14% of predicted 1s were correct ❗ (very poor)
**Note**: precision ("Am I correct when I predict?")

### 2. **Recall**

> Out of all actual examples of a class, how many did the model find?

* Class 0 → **0.33** → Found 33% of actual 0s
* Class 1 → **0.29** → Found 29% of actual 1s

Both are low → your model is **missing many true cases**

**Note**: recall ("Am I finding all the real cases?")

### 3. **F1-score**

> A balance between Precision and Recall

* Class 0 → **0.41**
* Class 1 → **0.19**

This shows overall performance per class → both are weak, especially class 1

Simple interpretation:
- **F1 = 1.0** → Perfect model
- **F1 = 0.0** → Very bad model
- **F1 = 0.5 or below** → Weak performance

### 4. **Support**

> Number of actual samples in each class

* Class 0 → **18 samples**
* Class 1 → **7 samples**

Your dataset is **imbalanced** (more 0s than 1s)

## Overall Metrics

### Accuracy = **0.32 (32%)**

* Only 32% of predictions are correct
  This is **very low** → model is not performing well

### Macro Average

* Treats both classes equally
* Precision: **0.34**, Recall: **0.31**, F1: **0.30**

Shows **poor performance across both classes**

### Weighted Average

* Takes into account class imbalance
* Precision: **0.43**, Recall: **0.32**, F1: **0.35**

Slightly better because class 0 has more samples

## Key Takeaways (Important)

1. **Your model is performing poorly overall**

   * Accuracy is low (32%)
   * F1 scores are low

2. **Class 1 is especially bad**

   * Precision = 0.14 → lots of wrong predictions
   * F1 = 0.19 → model struggles with this class

3. **Dataset is imbalanced**

   * More class 0 than class 1 → model may be biased

## What you should consider improving

* Use **more data**, especially for class 1
* Try **class balancing techniques** (e.g., SMOTE, class weights)
* Tune your Random Forest (n_estimators, max_depth, etc.)
* Check your features (maybe they’re not informative enough)

### Simple Analogy

Think of your model like a student:

* It gets only **32% correct** → failing
* It is **better at class 0**, but still not good
* It is **very bad at class 1**

In [45]:
# Compute the accuracy score (same as the score() method for classifiers) 
accuracy_score(y_test, y_preds)

0.44

In [46]:
# Create a confusion matrix
conf_mat = confusion_matrix(y_test, y_preds)
conf_mat

array([[7, 7],
       [7, 4]])

#### 5. Experiment to improve

The first model you build is often referred to as a baseline (a baseline is often even simpler than the model we've used, a baseline could be "let's just by default predict the most common value and then try to improve").

Once you've got a baseline model, like we have here, it's important to remember, this is often not the final model you'll use.

The next step in the workflow is to try and improve upon your baseline model.

How?

With one of the most important mottos in machine learning...

*Experiment, experiment, experiment!*

Experiments can come in many different forms.

But let's break it into two.

1. From a model perspective.
2. From a data perspective.

From a model perspective may involve things such as using a more complex model or tuning your models hyperparameters.

From a data perspective may involve collecting more data or better quality data so your existing model has more of a chance to learn the patterns within.

If you're already working on an existing dataset, it's often easier try a series of model perspective experiments first and then turn to data perspective experiments if you aren't getting the results you're looking for.

One thing you should be aware of is if you're tuning a models hyperparameters in a series of experiments, your reuslts should always be cross-validated (we'll see this later on!). 

[Cross-validation](http://scikit-learn.org/stable/modules/cross_validation.html) is a way of making sure the results you're getting are consistent across your training and test datasets (because it uses multiple versions of training and test sets) rather than just luck because of the order the original training and test sets were created. 

* Try different hyperparameters.
* All different parameters should be cross-validated.
    * **Note:** Beware of cross-validation for time series problems (as for time series, you don't want to mix samples from the future with samples from the past).
    
Different models you use will have different hyperparameters you can tune. 

For the case of our model, the [`RandomForestClassifier()`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), we'll start trying different values for `n_estimators` (a measure for the number of trees in the random forest).

By default, `n_estimators=100`, so how about we try values from `100` to `200` and see what happens (generally more is better)?

In [47]:
# # Try different numbers of estimators (trees)... (no cross-validation)
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 100 estimators...
Model accuracy on test set: 36.00%

Trying model with 110 estimators...
Model accuracy on test set: 48.00%

Trying model with 120 estimators...
Model accuracy on test set: 44.00%

Trying model with 130 estimators...
Model accuracy on test set: 40.00%

Trying model with 140 estimators...
Model accuracy on test set: 40.00%

Trying model with 150 estimators...
Model accuracy on test set: 44.00%

Trying model with 160 estimators...
Model accuracy on test set: 44.00%

Trying model with 170 estimators...
Model accuracy on test set: 52.00%

Trying model with 180 estimators...
Model accuracy on test set: 52.00%

Trying model with 190 estimators...
Model accuracy on test set: 56.00%

The metrics above were measured on a single train and test split.

Let's use [`sklearn.model_selection.cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) to measure the results across 5 different train and test sets.

We can achieve this by setting `cross_val_score(X, y, cv=5)`.

Where `X` is the *full* feature set and `y` is the *full* label set and `cv` is the number of train and test splits `cross_val_score` will automatically create from the data (in our case, `5` different splits, this is known as 5-fold cross-validation).

In [48]:
from sklearn.model_selection import cross_val_score

# With cross-validation
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)

    # Measure the model score on a single train/test split
    model_score = model.score(X_test, y_test)
    print(f"Model accuracy on single test set split: {model_score * 100:.2f}%")
    
    # Measure the mean cross-validation score across 5 different train and test splits
    cross_val_mean = np.mean(cross_val_score(model, X, y, cv=5))
    print(f"5-fold cross-validation score: {cross_val_mean * 100:.2f}%")
    
    print("")

Trying model with 100 estimators...
Model accuracy on single test set split: 36.00%
5-fold cross-validation score: 47.00%

Trying model with 110 estimators...
Model accuracy on single test set split: 40.00%
5-fold cross-validation score: 45.00%

Trying model with 120 estimators...
Model accuracy on single test set split: 48.00%
5-fold cross-validation score: 46.00%

Trying model with 130 estimators...
Model accuracy on single test set split: 44.00%
5-fold cross-validation score: 52.00%

Trying model with 140 estimators...
Model accuracy on single test set split: 52.00%
5-fold cross-validation score: 46.00%

Trying model with 150 estimators...
Model accuracy on single test set split: 56.00%
5-fold cross-validation score: 47.00%

Trying model with 160 estimators...
Model accuracy on single test set split: 48.00%
5-fold cross-validation score: 48.00%

Trying model with 170 estimators...
Model accuracy on single test set split: 44.00%
5-fold cross-validation score: 47.00%

Trying model with 180 estimators...
Model accuracy on single test set split: 48.00%
5-fold cross-validation score: 49.00%

Trying model with 190 estimators...
Model accuracy on single test set split: 40.00%
5-fold cross-validation score: 44.00%

Which model had the best cross-validation score?

This is usually a better indicator of a quality model than a single split accuracy score.

Rather than set up and track the results of these experiments manually, we can get Scikit-Learn to do the exploration for us.

Scikit-Learn's [`sklearn.model_selection.GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) is a way to search over a set of different hyperparameter values and automatically track which perform the best.

Let's test it!

In [49]:
# Another way to do it with GridSearchCV...
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

# Define the parameters to search over in dictionary form 
# (these can be any of your target model's hyperparameters) 
param_grid = {'n_estimators': [i for i in range(100, 200, 10)]}

# Setup the grid search
grid = GridSearchCV(estimator=RandomForestClassifier(),
                    param_grid=param_grid,
                    cv=5,
                    verbose=1) 

# Fit the grid search to the data
grid.fit(X, y)

# Find the best parameters
print(f"The best parameter values are: {grid.best_params_}")
print(f"With a score of: {grid.best_score_*100:.2f}%")

Fitting 5 folds for each of 10 candidates, totalling 50 fits
The best parameter values are: {'n_estimators': 150}
With a score of: 54.00%

We can extract the best model/estimator with the `best_estimator_` attribute.

In [50]:
# Set the model to be the best estimator
clf = grid.best_estimator_
clf

RandomForestClassifier(n_estimators=150)

In [52]:
# Fit the best model
model = clf.fit(X_train, y_train)

# Find the best model scores on our single test split
# (note: this may be lower than the cross-validation score since it's only on one split of the data)
print(f"Best model score on single split of the data: {clf.score(X_test, y_test)*100:.2f}%")

Best model score on single split of the data: 40.00%

#### 6. Save a model for someone else to use

When you've done a few experiments and you're happy with how your model is doing, you'll likely want someone else to be able to use it.

This may come in the form of a teammate or colleague trying to replicate and validate your results or through a customer using your model as part of a service or application you offer.

Saving a model also allows you to reuse it later without having to go through retraining it. Which is helpful, especially when your training times start to increase.

You can [save a Scikit-Learn model](https://scikit-learn.org/stable/model_persistence.html) using Python's in-built [`pickle` module](https://docs.python.org/3/library/pickle.html).

In [54]:
import pickle

# Save an existing model to file
pickle.dump(model, open("C:/Users/M.faisal/Desktop/ai_ml/ai_ml_projects/models/random_forest_model_1.pkl", "wb"))

In [55]:
# Load a saved pickle model and evaluate it
loaded_pickle_model = pickle.load(open("C:/Users/M.faisal/Desktop/ai_ml/ai_ml_projects/models/random_forest_model_1.pkl", "rb"))
print(f"Loaded pickle model prediction score: {loaded_pickle_model.score(X_test, y_test) * 100:.2f}%")

Loaded pickle model prediction score: 40.00%

For larger models, it may be more efficient to use [Joblib](https://joblib.readthedocs.io/en/stable/).

## Interactive UI
Let's try to build a lightweight inference UI inside **Jupyter Notebook**-good approach for quick validation before turning it into a full web app.

In [35]:
# pip install ipywidgets

In [34]:
#testing the to see if ipywidgets is installed
import ipywidgets as widgets
widgets.IntSlider()

IntSlider(value=0)

**Note**: Before running the dashboard, ensure that the model file exists and is in the same directory as your notebook.

In [58]:
# #Minimal check
# from joblib import dump, load
import joblib

# Save a model using joblib
# dump(model, "random_forest_model_1.joblib")
joblib.dump(model, "random_forest_model_1.joblib")

['random_forest_model_1.joblib']

In [59]:
# Load a saved joblib model
loaded_joblib_model = joblib.load("random_forest_model_1.joblib")
print(f"Loaded joblib model prediction score: {loaded_joblib_model.score(X_test, y_test) * 100:.2f}%")

Loaded joblib model prediction score: 40.00%

In [46]:
#Import Dependencies
import joblib
import numpy as np
import ipywidgets as widgets
from IPython.display import display, HTML

# Load trained model
model = joblib.load("random_forest_model_1.joblib")

#HTML header UI
display(HTML("""
<div style="
    background: linear-gradient(90deg, #1abc9c, #3498db);
    padding: 20px;
    border-radius: 10px;
    color: white;
    text-align: center;
    margin-bottom: 20px;">
    <h2>🩺 Diabetes Prediction Dashboard</h2>
    <p>Enter patient details and click Predict</p>
</div>
"""))

# Create INPUT widgets
Id = widgets.IntText(description="Id")
age = widgets.IntText(description="Age")
gender = widgets.FloatText(description="Gender")
bmi = widgets.FloatText(description="BMI")
BloodPressure = widgets.FloatText(description="BloodPressure")
Insulin = widgets.FloatText(description="Insulin")
glucose = widgets.FloatText(description="Glucose")
dpf = widgets.FloatText(description="DPF")

# Button + Output area
predict_button = widgets.Button(
    description="Predict",
    button_style='success'
)

output = widgets.Output()

# PREDICTION FUNCTION
def predict_diabetes(b):
    with output:
        output.clear_output()

        try:
            # Prepare input data
            data = np.array([[
                Id.value,
                age.value,
                gender.value,
                bmi.value,
                BloodPressure.value,
                Insulin.value,
                glucose.value,
                dpf.value
            ]])

            # Model prediction
            prediction = model.predict(data)[0]
            probability = model.predict_proba(data)[0][1]

            # Display result
            if prediction == 1:
                display(HTML(f"""
                    <div style="padding:15px;background:#ffe6e6;border-radius:8px;">
                        <h3 style="color:red;">⚠️ Diabetic</h3>
                        <p>Risk Probability: <b>{probability:.2f}</b></p>
                    </div>
                """))
            else:
                display(HTML(f"""
                    <div style="padding:15px;background:#e6ffed;border-radius:8px;">
                        <h3 style="color:green;">✅ Not Diabetic</h3>
                        <p>Risk Probability: <b>{probability:.2f}</b></p>
                    </div>
                """))

        except Exception as e:
            display(HTML(f"<p style='color:red;'>Error: {str(e)}</p>"))

# Link button to function
predict_button.on_click(predict_diabetes)

# Layout (FORM PIPELINE)
form = widgets.VBox([
    widgets.HBox([Id, age]),
    widgets.HBox([gender, bmi]),
    widgets.HBox([BloodPressure, Insulin]),
    widgets.HBox([glucose, dpf]),
    predict_button,
    output
])

# Display Dashboard
display(form);

VBox(children=(HBox(children=(IntText(value=0, description='Id'), IntText(value=0, description='Age'))), HBox(…